AllCops:
  Exclude:
    - 'db/migrate/20151210035820_init_schema.rb'
    - 'db/schema.rb'

Lint/BlockAlignment:
  Exclude:
    - 'lib/tasks/db.rake'

Lint/EndAlignment:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - '**/*_spec.rb'

Lint/Void:
  Enabled: false

Metrics/AbcSize:
  Max: 160

Metrics/ClassLength:
  Max: 500
  Exclude:
    - db/seeds/course_populator.rb

Metrics/CyclomaticComplexity:
  Max: 11

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 12

Performance/Count:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/Exit:
  Exclude:
    - lib/tasks/support/rspec_rerunner.rb

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/ReadWriteAttribute:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Validation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/BlockEndNewline:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/ExtraSpacing:
  Exclude:
    - 'bin/setup'
    - 'config.ru'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent
  Exclude:
    - 'app/models/course.rb'

Style/Lambda:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/MethodMissing:
  Exclude:
    - 'app/models/meetup_user.rb'

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 15

Style/NumericPredicate:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Style/WordArray:
  MinSize: 3
