require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TshirtCouponsController do

  def mock_tshirt_coupon(stubs={})
    @mock_tshirt_coupon ||= mock_model(TshirtCoupon, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all tshirt_coupons as @tshirt_coupons" do
      TshirtCoupon.stub(:all) { [mock_tshirt_coupon] }
      get :index
      assigns(:tshirt_coupons).should eq([mock_tshirt_coupon])
    end
  end

  describe "GET show" do
    it "assigns the requested tshirt_coupon as @tshirt_coupon" do
      TshirtCoupon.stub(:find).with("37") { mock_tshirt_coupon }
      get :show, :id => "37"
      assigns(:tshirt_coupon).should be(mock_tshirt_coupon)
    end
  end

  describe "GET new" do
    it "assigns a new tshirt_coupon as @tshirt_coupon" do
      TshirtCoupon.stub(:new) { mock_tshirt_coupon }
      get :new
      assigns(:tshirt_coupon).should be(mock_tshirt_coupon)
    end
  end

  describe "GET edit" do
    it "assigns the requested tshirt_coupon as @tshirt_coupon" do
      TshirtCoupon.stub(:find).with("37") { mock_tshirt_coupon }
      get :edit, :id => "37"
      assigns(:tshirt_coupon).should be(mock_tshirt_coupon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created tshirt_coupon as @tshirt_coupon" do
        TshirtCoupon.stub(:new).with({'these' => 'params'}) { mock_tshirt_coupon(:save => true) }
        post :create, :tshirt_coupon => {'these' => 'params'}
        assigns(:tshirt_coupon).should be(mock_tshirt_coupon)
      end

      it "redirects to the created tshirt_coupon" do
        TshirtCoupon.stub(:new) { mock_tshirt_coupon(:save => true) }
        post :create, :tshirt_coupon => {}
        response.should redirect_to(tshirt_coupon_url(mock_tshirt_coupon))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tshirt_coupon as @tshirt_coupon" do
        TshirtCoupon.stub(:new).with({'these' => 'params'}) { mock_tshirt_coupon(:save => false) }
        post :create, :tshirt_coupon => {'these' => 'params'}
        assigns(:tshirt_coupon).should be(mock_tshirt_coupon)
      end

      it "re-renders the 'new' template" do
        TshirtCoupon.stub(:new) { mock_tshirt_coupon(:save => false) }
        post :create, :tshirt_coupon => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tshirt_coupon" do
        TshirtCoupon.stub(:find).with("37") { mock_tshirt_coupon }
        mock_tshirt_coupon.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :tshirt_coupon => {'these' => 'params'}
      end

      it "assigns the requested tshirt_coupon as @tshirt_coupon" do
        TshirtCoupon.stub(:find) { mock_tshirt_coupon(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:tshirt_coupon).should be(mock_tshirt_coupon)
      end

      it "redirects to the tshirt_coupon" do
        TshirtCoupon.stub(:find) { mock_tshirt_coupon(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(tshirt_coupon_url(mock_tshirt_coupon))
      end
    end

    describe "with invalid params" do
      it "assigns the tshirt_coupon as @tshirt_coupon" do
        TshirtCoupon.stub(:find) { mock_tshirt_coupon(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:tshirt_coupon).should be(mock_tshirt_coupon)
      end

      it "re-renders the 'edit' template" do
        TshirtCoupon.stub(:find) { mock_tshirt_coupon(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tshirt_coupon" do
      TshirtCoupon.stub(:find).with("37") { mock_tshirt_coupon }
      mock_tshirt_coupon.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the tshirt_coupons list" do
      TshirtCoupon.stub(:find) { mock_tshirt_coupon }
      delete :destroy, :id => "1"
      response.should redirect_to(tshirt_coupons_url)
    end
  end

end
